version: '3'

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal
    environment:
      - MYSQL_DATABASE=bookmymovie
      - MYSQL_USER=superuser
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: .
    environment:
      - DB_HOST=database
      - MYSQL_USER=superuser
      - MYSQL_PASSWORD=
    ports:
      - "90:8080"
    networks:
      - internal
    depends_on:
      - setup_db
      - setup_tables

  setup_db:
    build:
      context: .
    environment:
      - DB_HOST=database
      - MYSQL_USER=superuser
      - MYSQL_PASSWORD=
    networks:
      - internal
    depends_on:
      - database
    entrypoint: php /app/setup/createDB.php

  setup_tables:
    build:
      context: .
    environment:
      - DB_HOST=database
      - MYSQL_USER=superuser
      - MYSQL_PASSWORD=
    networks:
      - internal
    depends_on:
      - database
      - setup_db
    entrypoint: php /app/setup/createTables.php


networks:
  internal:
