
version: '3'

services:
  database:
    image: mysql:5.7
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: .
    environment:
      - DB_HOST=database
    ports:
      - 90:8080
    networks:
      - internal
    entrypoint: /app/wait-for database:3306 -- sh /app/app-entrypoint.sh

networks:
  internal:

